### ISSUE TITLE
Need better application icons

### ISSUE THREAD

**Issue by d1vanov** [d1vanov/quentier#162]
The currently existing set of application icons was made by me and as long as I'm not a designer in any way, the icons look quite amateurish. Need something better.

Would gladly accept help from someone skilled in making icons. Have a look at [this](https://github.com/d1vanov/quentier/tree/master/resource/icons/app) page for the list of required sizes and stuff. Currently there are three sets of app icons: the default one (colored), the dark gray-scaled one (for light backgrounds) and the light gray-scaled one (for dark backgrounds). I'd like to keep such a separation, however, what's shown on the icon might need reconsideration: currently that's several pieces of paper covered with handwritten notes surrounded by planet rings like [Saturn's ones](https://en.wikipedia.org/wiki/Rings_of_Saturn). That somewhat symbolizes the ability to keep your notes in sync. I kind of like the concept but I'm open to other suggestions as well.

**Comment by polarathene** [comment]
You should be able to distribute the Breeze icons from KDE, they're for Qt apps, a comparable app is QOwnNotes where you might be able to see how similar icons in your app would look. Their website has screenshots showing off these icons/themes(but they don't appear to carry over to Windows at least, probably other DE/OS too).

If you are missing any particular icons from the Breeze set, the VDG(Visual Design Group) for KDE might be able to support by creating those for you. In exchange I guess, consider packaging for Linux via Flatpak which can then be used by KDE Discover or other app stores and package managers for many distro.

**Comment by d1vanov** [comment]
You misunderstood - this issue is about Quentier application icons, like [this one](https://github.com/d1vanov/quentier/blob/master/resource/icons/app/quentier_icon_256.png), not about the icon theme for the application to use.

**Comment by polarathene** [comment]
KDE VDG will also create Breeze app icons to better fit into their theme/DE if the app is popular enough. Perhaps less likely to happen any time soon. You may have luck with fivver or similar services for sourcing an artist affordably.

Usually icons will have a circular or square silhoutte, Google/Android has a good design guide for this and reasoning as to why. You can further read up on iconography :) You can probably make a fairly simple design with a few effects/gradient to make it pop a bit.

If you're fond of conveying sync, that tends to be symbolized as two strokes/arrows forming a circle/cycle. This could be applied to a stylized `Q` optionally placed on a circular or rounded rectangle background with gradient fill. The `Q` should be centered by it's ring rather than bounding box which would offset it visually(not great if you include a background fill layer and want fairly consistent padding).

**Comment by d1vanov** [comment]
Thanks for sharing your ideas. I think I won't be trying to draw the new app icon myself, instead will try to attract some artist to do it, first will try to get it for free :smile: failing that will consider paid options.

**Comment by d1vanov** [comment]
I've put a [couple](https://www.reddit.com/r/ArtisticHelp/comments/7ujkva/looking_for_volunteer_graphic_artist_to_draw_some/) of [requests](https://www.reddit.com/r/PixelArt/comments/7uqj9o/job_looking_for_volunteer_graphic_artist_to_draw/) for help with icons in some reddit subs and got one response from a designer who agreed to try making better icons for Quentier. So this one can be assumed being worked on currently.
