### ISSUE TITLE
Feature Request: 'git repository' as storage option.

### ISSUE THREAD

**Issue by timoc** [d1vanov/quentier#163]
The Evernote backend has a whole versioning scheme setup which tracks the history of your notes. I would like to be able to export my versioned evernote notes, and quentier notes into a git repository (presumably containing XML or similar), so that i can synchronize the repos across desktops without being online, and maintain a backup of my online resources.

**Comment by d1vanov** [comment]
Thanks for the suggestion! Notes history feature is only available to Premium Evernote accounts. For now I don't plan on supporting Premium-only features unless probably they don't require the actual use of Evernote API (like presentation mode). Or unless someone else would like to take this task. Just because there is still so much to do to get the basic version of the app working reliably.

Right now you can manually synchronize the unversioned local storage database across your devices if you wish. Moreover, using `--storageDir` command line option you can point the app the location of your notes & other stuff storage (the default storage dir is mentioned [here](https://d1vanov.github.io/quentier/blog/quentier-brief-overview/)). You can also probably write some scripts accessing the local storage database directly, the schema can be found [in this method](https://github.com/d1vanov/libquentier/blob/master/src/local_storage/LocalStorageManager_p.cpp#L4159).

**Comment by d1vanov** [comment]
Also, if you'd like to use git as the backend for your notes storage, you might wish to take a look at [MyTetra](https://github.com/xintrea/mytetra_dev) app.

**Comment by timoc** [comment]
I cannot read russian - google is helping :)

Looks cool - Would it not make more sense to see if you guys can work together to share these things? You are both using QT, and so if you migrated these features to plugins, you should theoretically be able to share your work on collection and persistence infrastructures, allowing you both to focus more on the features you want rather than the plumbing to connect to evernote/git etc.

**Comment by d1vanov** [comment]
I'm afraid such storage abstraction is just way too abstract for being practical: for one thing, there are a lot of differences between storing things as plain files on the hard drive and as blobs within a database. For example, good luck implementing as fast full text search using plain text files as the one SQLite database is capable of. For another thing, storing things in a git repository and in Evernote are different enough approcahes to have too less in common to even bother creating any kind of high-level abstraction covering both of them.

That's my view on it. Quentier was born with the mission to become free & open source Evernote client, local accounts feature just cropped up at some moment and I implemented it because it was simple - just get rid of the synchronization stuff and it's done. So if you use Evernote or would just like to take local notes using Evernote's data model - notebooks, tags, notes, resources (attachments to notes) - be my guest :smiley: For other purposes there are other apps.

**Comment by timoc** [comment]
If you look at the problem from the storage perspective, then all you are doing is flattening out an XML DOM from the evernote EML(?) markup, into your sqlite backend. If you treat the evernote knowledge-base as a DOM that you serialise then you can use the DOM as an internal abstraction that should work as a shared approach to knowledge management, as long as you use the same XML/XHTML representation.
But as you say, if you are tied to the Evernote XML dom, then your ORM is going to be (presumably) tightly coupled to your SQL design.

**Comment by d1vanov** [comment]
That's exactly the case, Quentier's local storage database schema closely follows [Evernote data model](https://dev.evernote.com/doc/articles/data_structure.php) with a few additions.

**Comment by d1vanov** [comment]
I kept this one open to consider this in future but it doesn't seem like it would be possible to implement in any foreseeable future. As I need to keep the number of issues somewhat manageable, I'm closing this one. If someone would like to have a note-taking app using git repo as a backend, I recommend looking at [MyTetra](https://github.com/xintrea/mytetra_dev) app.
