### ISSUE TITLE
Selecting a notebook in favorites view doesn't change the notes filter

### ISSUE THREAD

**Issue by MikeStutzzzz** [d1vanov/quentier#172]
When adding a notebook to favorites when clicking it, the notebook contents do not show in the filters.
I tried to run a Debug or Trace but my 32Gigs of RAM maxed out Immediately and the app died.

**Comment by d1vanov** [comment]
Thank you for reporting this! It is simply an overlooked thing, indeed the selection of a notebook within favorites view doesn't trigger it the note filter, unlike notebooks view.

Need to think on the details of the solution so that they stay in line with #147 and #148.

On the problem with logging - yeah, the current design of the log viewer is not really great and can't really handle a lot of logs - there's #143 to deal with it somehow. As a workaround, to start collecting the log you can open the log viewer, change the log level to "Debug" or "Trace" and then just close the log viewer. The saved log would go to either of the following locations, depending on the platform you use:

1. `~/.quentier/logs-quentier` on Linux
2. `~/Library/Application Support/quentier.org/Quentier/logs-quentier` on Mac
3. `C:\Users\%USERNAME%\AppData\Roaming\Quentier\logs-quentier` on Windows

**Comment by d1vanov** [comment]
Done in development branch.
