### ISSUE TITLE
Can't add evernote account

### ISSUE THREAD

**Issue by stbain** [d1vanov/quentier#175]
When using Quentier 0.4.0 under Fedora 28, attempting to add an Evernote account results in the following error being displayed in the bottom status bar:

_"Can't switch to new evernote account: failed to sync user data, edam protocol version check failed thriftexception type = 2 thriftexception invalid message type"_

**Comment by stbain** [comment]
~ $ sudo dnf info quentier
Last metadata expiration check: 0:30:46 ago on Tue 19 Jun 2018 03:58:58 PM EDT.
Installed Packages
Name         : quentier
Version      : 0.4.0
Release      : 0.3.20180301.git8226e31.fc28
Arch         : x86_64
Size         : 6.3 M
Source       : quentier-0.4.0-0.3.20180301.git8226e31.fc28.src.rpm
Repo         : @System
From repo    : fedora
Summary      : Cross-platform desktop Evernote client
URL          : https://github.com/d1vanov/quentier
License      : GPLv3
Description  : Quentier is a cross-platform desktop note taking app capable of
             : working as Evernote client. You can also use Quentier for local
             : notes without any connection to Evernote and synchronization.

~ $

**Comment by d1vanov** [comment]
Hmm, it seems some users of Nixnote2 have a similar problem (Nixnote2 uses QEverCloud as well as Quentier and the error you observe comes from QEverCloud) and one of them [claims](https://github.com/baumgarr/nixnote2/issues/439#issuecomment-395686999) the reason is in GCC 8, the version built using GCC 7.3 works fine. I'll try to investigate more about this topic but I'm not a Fedora user myself so can't promise I'd be able to come up with anything useful. In the meantime you can try to use the AppImage.

**Comment by d1vanov** [comment]
@stbain, could you please attach Quentier's log file: `$HOME/.quentier/logs-quentier/Quentier-log.txt`? It might contain some information useful for further troubleshooting.

@eclipseo, would it be possible to use clang instead of gcc to build at least QEverCloud (and at most also libquentier and Quentier) at copr for Fedora 28? For the build procedure it would require additional arguments to `cmake`: `cmake <...> -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++)`. Since things seem to work for users of Fedora 26 and Fedora 27, it would be preferable to switch the compiler only for Fedora 28 (if copr has any switches for specific distro versions), just to see if it would make the issue go away. If it would, it could be a temporary solution for users of that copr repo, until I manage to figure out what's wrong with gcc builds.

**Comment by stbain** [comment]
[Quentier-log.txt](https://github.com/d1vanov/quentier/files/2117867/Quentier-log.txt)
@d1vanov attached

**Comment by d1vanov** [comment]
Thanks!

Meanwhile, I believe I found the root cause: QEverCloud has a large almost copy-paste chunk of code from [Apache Thrift]() library. Some of that code does scary things on the edge of those allowed by the language standard. Such things are prone to break if any compiler optimization goes wrong. I can see the following issue within the Apache Thrift library's bugtracker: https://issues.apache.org/jira/browse/THRIFT-4584. So I believe it suffers from the very same issue with newish gcc. There's a [comment])https://issues.apache.org/jira/browse/THRIFT-4584?focusedCommentId=16514772&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16514772) there which suggests a workaround:

> There is an optimization issue in GCC 8.0 and 8.1 which affects Apache Thrift's binary protocol implementation. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85882 . The issue occurs for optimizations >= -O2. Problem can be avoided by disabling any of
`-ftree-vrp -finline -ftree-fre`
> Will be fixed in GCC 8.2 and GCC 9.0.

Perhaps it's worth trying this workaround.

**Comment by d1vanov** [comment]
@stbain, I've enabled Fedora 28 builds at OpenSUSE build service, can you please try to uninstall quentier, libquentier and qevercloud which you have now and then install fresh versions from OBS:
```
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:d1vanov:quentier-master/Fedora_28/home:d1vanov:quentier-master.repo
dnf install quentier
```

**Comment by valmar** [comment]
@d1vanov Thanks this seems to work. Very appreciated!

**Comment by d1vanov** [comment]
Glad this trick worked, thanks for verifying! It looks like Fedora's quentier package took priority due to the way its version string is composed. It's fine for now since this issue was in the library, not the app itself.

**Comment by eclipseo** [comment]
Sorry guys, I have been following the issue but I'm on vacation right now, I'll try to push an update ASAP.

**Comment by d1vanov** [comment]
No worries, some solution has already been provided by introducing an OBS repo for Fedora 28. Enjoy your vacation!
