### ISSUE TITLE
Some shortcuts are not working in the note editor

### ISSUE THREAD

**Issue by zergiuzz** [d1vanov/quentier#187]
Tell me please, how to adjust "copy+past" in the editor, undo and redo work, and there is no CTRL+C and CTRL+V.

**Comment by d1vanov** [comment]
Hi there! Yes, it's better to write in English so that non-Russian speaking folks can also read the question and answers.

Question translation: how to set up copy and paste shortcuts in the note editor: undo and redo are working, copy and paste are not.

Some more information is actually required to answer this: which OS are you running Quentier on - Linux, Windows, Mac? Which version you are running, where did you get it from - i.e. for Linux is it AppImage? If so, are you using the one from continuous-master release or continuous-development release? Or maybe you are using a PPA for Ubuntu?

In general, some problems might actually be present with shortcuts, especially when QtWebEngine-based note editor is used: keyboard shortcut events need to be intercepted in a special way for the purposes of implementing the undo-redo stack, something could easily fall through the cracks.

It would be useful to see Quentier version info ("Help" -> "About Quentier") and the trace level log when you press Ctrl+C and/or Ctrl+V. How to collect the log is described [here](https://github.com/d1vanov/quentier/wiki/Collecting-Quentier-logs-for-troubleshooting).

In theory such shortcuts as copy and paste should come from system defaults but you can also try to specify them manually: open the preferences dialog via going to "Service" -> "Settings" menu, there open "Shortcuts" tab and override the hotkey for copy and paste actions of the note editor.

Russian version:

День добрый, да, лучше писать на английском, просто чтобы другие люди, не знающие русского языка, тоже могли читать issues.

Хотелось бы узнать поподробнее, какая версия программы используется и на какой OS? Если Linux, то используется ли AppImage или, может быть, версия из PPA для Ubuntu или что-то другое.

Некоторые проблемы с хоткеями могут быть, особенно если редактор собран с использованием QtWebEngine, там приходится сложным образом перехватывать хоткеи, чтобы понимать, какие действия совершаются, чтобы иметь возможность реализовать undo/redo.

Было бы неплохо увидеть, во-первых, информацию об используемой версии программы ("Help" -> "About Quentier"), а также логи уровня trace при попытке сделать Ctrl+C & Ctrl+V. Вот [тут](https://github.com/d1vanov/quentier/wiki/Collecting-Quentier-logs-for-troubleshooting) рассказано, как собрать лог.

Ещё кое-что: теоретически хоткеи Ctrl+C & Ctrl+V должны приходить из системных дефолтов, но если этого вдруг не случилось, можно открыть диалог настроек через "Service" -> "Settings" меню, в открывшемся диалоге выбрать вкладку "Shortcuts" и там настроить хоткеи для copy & paste для editor.

**Comment by zergiuzz** [comment]
Linux Mint 18.3. I have installed the program from a repository Ubuntu. Quentier 0.4.0 Qt 5.5.1. In logs there is nothing. I have set in settings new hot keys and has helped. Here still that - 
If to cause a dialog box that to copy and insert there without the hot keys. But if to enter the edit menu that there they are. I can't make a screenshot with the caused dialog box.

**Comment by d1vanov** [comment]
Ok, thanks for reporting that problem with shortcuts dialog, I'll take a look into it a bit later.

**Comment by robert7** [comment]
немного говорю по-русски ... but wouldn't understand all :) 
didn't use my russian skills even longer then C++ :)

**Comment by d1vanov** [comment]
> If to cause a dialog box that to copy and insert there without the hot keys. But if to enter the edit menu that there they are. I can't make a screenshot with the caused dialog box.

As I understood, it is about the items of the context menu not having keyboard shortcuts displayed near them while in the app's edit menu the shortcuts are displayed. Code-wise I can see that shortcuts actually are being set on the context menu actions but they are still not displayed. Quick googling has lead me to [this thread](https://forum.qt.io/topic/86575/action-shortcut-missing-in-context-menu/12) on Qt forum which explains that Qt has never displayed shortcuts for actions in the context menu. So, unfortunately, I can't do anything with it.

Since the original problem of this issue was solved via manual entering of shortcuts for copy and paste, I'm closing this one.
