### ISSUE TITLE
Automatic source code formatting and linting

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#194]
I understand the importance of having consistent code style in any software project.

Its no problem for you to pick the style you like ([like you did](https://github.com/d1vanov/quentier/blob/master/CodingStyle.md)).
But its **quite a pain to do it manually**. Partially because you picked some unique non-standard style 
and it also contains some fairly special requirements like "... However, if the operator body involves many lines, say, more than 6 or 7". But thats **not the problem - if there is automatic tool for reformatting**.

Automatic code linting is also according to [github open source best practices](https://opensource.guide/best-practices/#use-tools-to-automate-basic-maintenance-tasks). 

> ... However, if your standards are too complicated, they can increase the barriers to contribution. Make sure you’re only adding enough rules to make everyone’s lives easier.

=> :) currently your style guide makes it bit more difficult, but with auto format you will have your style & no one will be forced to do it manually.

There are few tools available for C++ which can to the task - see e.g. http://doc.qt.io/qtcreator/creator-beautifier.html
I did use astyle for very short time http://astyle.sourceforge.net/ - it worked quite well. The base setup took me like an hour.

You will probably don't able to to config e.g. astyle or clangformat to follow to 100% the style you picked, but you could get pretty close. Then you could reformat whole source code as one time operation. Then you can turn on style linting on pull requests.

Its not really urgent, but for **long term cooperation I see it quite important**. Also it will ease adoption of contributions from other people - I hope later more will join.

For me personally I always use IDE to auto format the code. Now I can't do it. If there will be auto-format script, I can configure IDE to come closer to selected style and before PR just reformat changed files.

**Comment by d1vanov** [comment]
Thanks for the suggestion. I think in the world of C++ there's no such thing as a standard style. Some popular large projects have somewhat established styles and other projects are encouraged to pick one of them so as to make it somewhat familiar to most developers - there are things like LLVM coding style, Google coding style etc.

I actually simply picked the coding style we use at work since it's the one I'm mostly familiar with. I didn't put very much thought into it. I haven't heard for any of our devs - like, several dozens to a hundred of men - using some code autoformatting tool, to be honest. However, very few of them use any IDE, most just write code in vim :smiling_imp:

I guess I won't be looking into this any time soon since there are more important things to do but let's keep it open for now and see whether some day it would be possible to consider this.

**Comment by robert7** [comment]
Using IDE is about effectivity. By pickup the right tools, you can get 10-30% faster (I guess even more for some tasks). And the numbers add up in the long run.

>I guess I won't be looking into this any time soon since there are more important things to do but let's keep it open for now

I agree that fixing of the sync is now more important. 

I suggest: don't close, you can mark it low-prio. We can reconsider after let say 3 weeks.

I would be will to implement format linting, but we would need to discuss it before; now let it wait.

**Comment by robert7** [comment]
I still this would be worth doing sometime, but now its not priority; so I close it.
