### ISSUE TITLE
Evernote "Synchronisation was stopped" error

### ISSUE THREAD

**Issue by franz-sp** [d1vanov/quentier#216]
Hi again,

as per indications in #214 I opened a new issue thread about the "Synchronisation was stopped" error.

I found two occurrences of `MainWindow::onSynchronizationManagerFailure` at lines 1661 and 1832 or the attached log file.
The file is so big because the first occurrence actually happens after a very long note coming from the Evernote clipper, and I suppose it could be somehow related to the error. I deleted several repeating [Trace] chunks between the two occurrences to make the file lighter.

Best,

F

[QuentierSelectedLogSync.txt](https://github.com/d1vanov/quentier/files/2313768/QuentierSelectedLogSync.txt)

**Comment by d1vanov** [comment]
Thanks! I'll take a look into it a bit later.

**Comment by d1vanov** [comment]
Couldn't resist the temptation and looked into the log right now: the problem occurs because of some attachment to some note:
```
2018-08-22 19:23:24.949 CEST libquentier/src/synchronization/SynchronizationManager_p.cpp:628 [Debug]: SynchronizationManagerPrivate::onRemoteToLocalSyncFailure: Failed to add the data item fetched from the remote database to the local storage, can't do the partial update of note's resources, found invalid resource linked with note, Resource's recognition size is not equal to the actual recognition data size: 575
```
It seems this was caused by the following resource recognition data:
```
  Recognition data: {
  size = 575;
  bodyHash = c000b87fb8642e868a93b88b09d82b42;
  body = <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE recoIndex SYSTEM "http://xml.evernote.com/pub/recoIndex.dtd"><recoIndex docType="picture" objType="image" objID="26eb49857b206eca680f7e8f6d1cf641" engineVersion="2.1.21.3" recoType="service" lang="en" objWidth="66" objHeight="22"><item x="15" y="6" w="36" h="10"><t w="45">CHIUDI</t><t w="42">CHIUD1</t><t w="42">CHIUD&apos;</t><t w="38">CHLUDI</t><t w="37">GHIUD&apos;</t><t w="37">CHIUD!</t><t w="19">CHLUDL</t><t w="19">CHTUDI</t><t w="19">CHIUM</t><t w="19">CHILLY</t><t w="19">CHILLS</t><t w="19">0111001</t><t w="19">0131001</t></item></recoIndex>;
  raw recognition body content: <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE recoIndex SYSTEM "http://xml.evernote.com/pub/recoIndex.dtd"><recoIndex docType="picture" objType="image" objID="26eb49857b206eca680f7e8f6d1cf641" engineVersion="2.1.21.3" recoType="service" lang="en" objWidth="66" objHeight="22"><item x="15" y="6" w="36" h="10"><t w="45">CHIUDI</t><t w="42">CHIUD1</t><t w="42">CHIUD&apos;</t><t w="38">CHLUDI</t><t w="37">GHIUD&apos;</t><t w="37">CHIUD!</t><t w="19">CHLUDL</t><t w="19">CHTUDI</t><t w="19">CHIUM</t><t w="19">CHILLY</t><t w="19">CHILLS</t><t w="19">0111001</t><t w="19">0131001</t></item></recoIndex>;
  };
```
That "raw recognition body content" indeed has another size in bytes as demonstrated by https://mothereff.in/byte-counter:
![bytes_count](https://user-images.githubusercontent.com/2050562/44518079-e3275880-a6b8-11e8-93a1-581198233e67.png)

As long as this resource came from Evernote, it appears that Evernote doesn't double-check the integrity of resource data information while Quentier does. Perhaps it should not do so, at least not for the data coming to it from Evernote. I'll think what and where needs to be fixed here but the problem is clear. Thank you very much for reporting it!

**Comment by msbentley** [comment]
Just to say that I've hit the same problem - what is more of an issue for me is that the app locks up on this error, and I can't do anything other than kill it and start again until the sync hits the next such note (running the dev version from the ubuntu ppa)

**Comment by d1vanov** [comment]
> The error I received was related to the mismatch of note resource recognition data size, so I assumed it was related

Ok, in this case it's most likely indeed related. Sorry, I thought your words about hitting the same problem were about hitting the problem of initial sync stopping :flushed:

> The app becomes non-responsive during the "sync chunk download" part of the initial sync

I guess It happens because sync chunks are downloaded in GUI thread in a synchronous i.e. blocking fashion. I was hoping it won't lead to problems with responsiveness since since chunks typically don't contain much information (i.e. neither heavy resource blobs nor note content) but apparently having many enough sync chunks to download would hurt responsiveness. Will need to find some solution for this - either move it to a separate thread or download sync chunks in asynchronous i.e. non-blocking fashion.

**Comment by d1vanov** [comment]
I decided to try a simple fix - just remove the check for resources' size fields consistency with their data bodies. The new build is [available](https://github.com/d1vanov/quentier/releases/download/continuous-development/Quentier_mac_x86_64.zip). @franz-sp, could you please download and try it?

**Comment by franz-sp** [comment]
I’m trying it. I’ll post the results tomorrow.

--
Arch. Francesco Spanedda

Università di Sassari
Facoltà di Architettura di Alghero
Dipartimento di Architettura, Design e Urbanistica (DADU)
Palazzo del Pou Salit - Piazza Duomo 6
07041 Alghero (SS) - Italia
T +39 079 9720400
M +39 347 4425217
F +39 079 9720420
E francesco.spanedda@uniss.it
Il 24 ago 2018, 10:41 +0200, Dmitry Ivanov <notifications@github.com>, ha scritto:

**Comment by franz-sp** [comment]
Hi again,

it seems that Quentier was able to succesfully download my notes from Evernote on both Mac machines. 👍 

My Evernote notes are 1694. After a certain amount of notes (around 400) there is a strange misalignment between the number of notes appearing in the "Notebooks" window, which grows during the download, and the number of downloaded notes in the status bar. 
I attach a screenshot that show this behaviour.
When I took the screenshot all my notes were downloaded, but the status bar was still showing a download in progress, and the sync icon was still spinning (obviously the screenshot can't show this :) ).
I'm now trying to write notes on Quentier and see how they sync with the Evernote account.

Best,

F

**Comment by franz-sp** [comment]
Ok, new notes written in Quentier are regularly added to Evernote... 
Everything seems work at it should now!

Many thanks!

👍

**Comment by d1vanov** [comment]
Ok, glad to hear it's working now! Thanks for checking, will deliver the fix to the stable branch as well.

The misalignment between the number of notes you mentioned looks strange. I don't have a plausible explanation for this off the top of my head. Are there any warning/info/error entries in the log?

**Comment by d1vanov** [comment]
Still don't have the explanation for stale sync progress notification but I guess it's too late for getting any more info on this. Will look into it in future.

The fix to the original problem was delivered to master branch as well, so closing this issue.
