### ISSUE TITLE
Does Quentier depend on KWallet?

### ISSUE THREAD

**Issue by eclipseo** [d1vanov/quentier#259]
I'm the Quentier maintainer for Fedora.
One of the GNOME user noticed an error:

 `Failed to write the oauth shard id to the keychain: could not open wallet: org.freedesktop.dbus.error.serviceunknown; the name is not activatable`

He solved it by installing KWallet.
I thought Quentier was not depending on any KDE apps. Is KWallet a hard requirement? It is not mentioned in the INSTALL document.

Note that he has gnome-keyring up and running.

**Comment by d1vanov** [comment]
Quentier itself does not depend on KWallet. But Quentier's core library, libquentier, depends on another library, [QtKeychain](https://github.com/frankosterfeld/qtkeychain). That library is a unified Qt interface to the platform's native keychain. In particular, as its README.md says,
`Linux/Unix: If running, GNOME Keyring is used, otherwise qtkeychain tries to use KWallet (via D-Bus), if available`
If gnome-keyring is up and running, the library should use it. If it doesn't, perhaps it's a bug which should be reported to that library's maintainers.

**Comment by eclipseo** [comment]
> If gnome-keyring is up and running, the library should use it. If it doesn't, perhaps it's a bug which should be reported to that library's maintainers.

I'm trying in a VM, gnome-keyring is running, yet Quentier outputs the following error:
`libquentier-625eb2864605588b4ffa0562fe8cf06b17395a6b/src/synchronization/SynchronizationManager_p.cpp @ 1630 [Warn]: Attempt to write the authentication token returned with error: error code 7, Could not open wallet: org.freedesktop.DBus.Error.ServiceUnknown; The name is not activatable`

**Comment by eclipseo** [comment]
My distro version of QtKeychain is outdated. I will seek the maintainer to update it and retry.

**Comment by eclipseo** [comment]
It seems QtKeychain depends on libgnome-keyring being present and not gnome-keyring only.
