### ISSUE TITLE
Can't sync with Evernote

### ISSUE THREAD

**Issue by big-ole-barge** [d1vanov/quentier#345]
Hey so I love the app but I can't get it it to sync up with Evernote. I go through the process to add the account and I get an email saying Evernote now has access to Quentier but no account is actually added to Quentier. I'm using it through the appimage on arch linux with i3 if that's important.

This is what shows up in the terminal as I do this.

```
libquentier/src/note_editor/SpellChecker_p.cpp:409 [Info]: No previously cached dic/aff files seem to actually exist anymore, re-scanning the system for diction
QNetworkRequest::setHeader: QVariant of type QNetworkCookie cannot be used with header Cookie
QNetworkRequest::setHeader: QVariant of type QNetworkCookie cannot be used with header Cookie
libquentier/src/synchronization/SynchronizationManager_p.cpp:2391 [Warn]: Failed to write the OAuth token to the keychain, Unknown error
libquentier/src/synchronization/SynchronizationManager_p.cpp:2421 [Warn]: Failed to write the shard id to the keychain, Unknown error
bin/quentier/src/MainWindow.cpp:1898 [Error]: MainWindow::onSynchronizationManagerFailure: Failed to write the OAuth token to the keychain, Unknown error
bin/quentier/src/MainWindow.cpp:1898 [Error]: MainWindow::onSynchronizationManagerFailure: Failed to write the shard id to the keychain, Unknown error
bin/quentier/src/MainWindow.cpp:1880 [Info]: MainWindow::onSynchronizationStopped
bin/quentier/src/MainWindow.cpp:1880 [Info]: MainWindow::onSynchronizationStopped
bin/quentier/src/MainWindow.cpp:1941 [Info]: MainWindow::onAuthenticationFinished: success = false, error description = Can't authenticate to Evernote, account = 
QEverCloud/QEverCloud/src/Http.cpp:146 [Warn]: ReplyFetcher error: code = QNetworkReply::AuthenticationRequiredError, description: Host requires authentication; http status code: 401
QEverCloud/QEverCloud/src/OAuth.cpp:154 [Warn]: Failed to acquire temporary token: Host requires authentication
bin/quentier/src/MainWindow.cpp:1941 [Info]: MainWindow::onAuthenticationFinished: success = false, error description = Can't authenticate to Evernote: Host requires authentication, account = 
```

**Comment by d1vanov** [comment]
Hi there!
Thanks for reporting this issue. From these log entries it seems that the root cause is inability of Quentier to interact with the system keychain to store some values which should not be stored in plain text. Quentier uses [qtkeychain](https://github.com/frankosterfeld/qtkeychain) library to interact with the system keychain. The library can work with separate different backends: if running, gnome keyring is used, otherwise qtkeychain tries to use KWallet (via D-Bus). Please make sure that in your system there is one of these backends installed.

If the backend is present on your system, it might be an issue with AppImage packed app that it can't interact with the system keychain properly. I have a native build of Quentier for Arch Linux set up at OpenSUSE build service but for some reason I can't get the convenient link with installation instructions (I knew where it was before but somehow it's gone now). The repo itself is [here](https://download.opensuse.org/repositories/home:/d1vanov:/quentier-master/Arch_Community/x86_64/), maybe you can figure how to add it to your package manager. If you can do it, I suggest trying the native build for Arch Linux. If the error is connected to AppImage format somehow, the problem might solve itself.

**Comment by d1vanov** [comment]
This issue is not the first one about problems with the system keychain so I intend to introduce an option to skip using it altogether or fall back to storing the token unencrypted automatically if commucation with the keychain fails - d1vanov/libquentier#158

**Comment by big-ole-barge** [comment]
Very informative solution/explanation, thank you!

**Comment by d1vanov** [comment]
You are welcome! Please let me know if any of the above measures I wrote about would help.

**Comment by d1vanov** [comment]
I implemented the fallback scheme which AppImage builds would use: Quentier would still try to use QtKeychain for auth token storage but it would also store the token locally in `QSettings` in encoded/obfuscated form. Reading would be attempted from QtKeychain first and if it fails it would use the locally stored value. That way changes should be backward compatible for existing users while helping with setups in which QtKeychain for some reason doesn't work properly.

For now this functionality is only available in unstable AppImage build which you can try if you wish, with AppImage it's quite simple to switch between stable and unstable builds. But beware, it's called unstable for a reason - changes land there first and things can occasionally break even though I try not to break them.
The change would get into the stable version eventually - from time to time I stabilize the unstable branch and merge it to stable. I hope the next time it would happen in early 2021.
