### ISSUE TITLE
The program crashes

### ISSUE THREAD

**Issue by ra3ggi** [d1vanov/quentier#346]
The program crashes immediately after syncing
[a12f8695-4554-463b-afbb31bc-3848ca4a.zip](https://github.com/d1vanov/quentier/files/5536488/a12f8695-4554-463b-afbb31bc-3848ca4a.zip)

**Comment by d1vanov** [comment]
Hi,
thank you for reporting this. If you can reproduce it, could you please also attach the text displayed in the crash handler window? It would make the investigation much easier.

**Comment by d1vanov** [comment]
It would also be helpful to know whether you used stable or unstable version of Quentier, distro version, where did you install it from - launchpad, AppImage, OBS repo etc.

**Comment by d1vanov** [comment]
One more thing which could be useful: launch quentier from command line under gdb like this:
```
gdb /usr/bin/quentier
```
Then when the prompt shows up, type `run` there and press Enter. Then make the program crash and then type in the gdb prompt `thread apply all bt` and paste the output of this command here. This method should provide the most useful information.

**Comment by d1vanov** [comment]
I tried my best to investigate given only the attached file but so far I haven't got much success. The only things I found out are these:
1. Libquentier version being used seems to come from unstable repository for Debian 10 from OBS. Ot at least its debugging symbols signature matches that of the said repository
2. But Quentier's debugging symbols signature doesn't match it for some reason so I'm not sure I guessed the distro version and used Quentier version correctly.
3. The last stack frame belonging to libquentier before the crash has something to do with working with resources embedded into the note: it seems there was an attempt to open the attachment within the note via pressing a button on it. Furthermore, I can see a stack frame attempting to print the rotation direction for image attachment.
4. Many stack frames after this in the thread which ended up crashing belong to Qt internals, in particular to QtWebKit. It might very well be that the crash is caused by some Qt issue.

Since QtWebKit is deprecated, I need to switch Debian builds on OBS to QtWebEngine really. I might also drop the support for Debian oldstable and leave only the stable one. Because who uses oldstable Debian on desktop anyway?

@ra3ggi Alex, if you can reproduce the issue, please do and attach more info as I explained in [this comment](https://github.com/d1vanov/quentier/issues/346#issuecomment-726735188). Furthermote, if it reproduces consistently, please try to get a backtrace with gdb as explained in [this comment](https://github.com/d1vanov/quentier/issues/346#issuecomment-726747956). Otherwise I'm afraid I can't figure out the exact reason and can only blame QtWebKit and try to switch the existing builds away from using it.

**Comment by d1vanov** [comment]
I believe I did the best I could do here:
1. I switched all OBS builds to using QtWebEngine instead of QtWebKit. Right now the only shipped builds which use QtWebKit are those from launchpad repository for Ubuntu Xenial. It's because it has Qt 5.5.1 which is quite old and its QtWebEngine version is even buggier than QtWebKit. It has about half a year to live so dropping support for it would mean I can remove the support for using QtWebKit instead of QtWebEngine for good.
2. I set up issue templates for this GitHub repository which encourage users to provide more info in bug reports and crash reports. I sincerely hope it would help my troubleshooting attempts.

@ra3ggi Alex, I suggest you to update. If I was right that your version was coming from an OBS repo then you should not experience problems originating from QtWebKit anymore. If by any chance you use Ubuntu Xenial and launchpad repository for it then, well, I can't do much to help but recommend to update the distro. If you manage to reproduce the crash again, please open a new issue and please use the issue template hints to provide more info for the investigation next time.
