### ISSUE TITLE
Problem with search in note (bug or not bug?) [bug] 

### ISSUE THREAD

**Issue by ra3ggi** [d1vanov/quentier#382]
Problem with search in note
1. open a search in the note.
2. Find the word you need.
3. Put the cursor near it
4. Close the search in the note.
5. The cursor flies to the beginning of the note and we lose the position of the found word.

**Comment by d1vanov** [comment]
I'll take a look but most likely the behaviour is caused by highlighting of searched words within the note: in order to highlight some words, the HTML document within the editor is changed - tags highlighting words are added. When you close the search dialog, these tags are removed and the position of the cursor is lost because it used to correspond to another document.

**Comment by ra3ggi** [comment]
Yes, but then why search if you lose the search position when you close the search? There is no such thing in html documents. In the browser if you found the word - the cursor stays on the position even when you close the search.

**Comment by d1vanov** [comment]
I agree it would be good not to lose the position of the cursor. I'll take a look to see if I'd be able to implement preserving the cursor position.
In browser highlighting works differently though, it doesn't have to alter the contents of the displayed web page.
