### ISSUE TITLE
Problems with inserting a picture. [bug] 

### ISSUE THREAD

**Issue by ra3ggi** [d1vanov/quentier#384]
If you just paste a picture into a note, the program does not understand that there are changes in the note. 
Even the "Save" icon does not become active. 
Because of this there are problems with synchronization. 
If you add text, "Save" becomes active immediately.

**Comment by d1vanov** [comment]
Tried to fix in unstable version, updates will be ready in a few hours.

**Comment by d1vanov** [comment]
To clarify a bit: it is intended that after inserting any attachment to the note save button is disabled - it is because the note is automatically saved. The problem with sync was caused by the fact that during saving the locally modified flag was not set for the note so it wasn't sent back to Evernote during sync. Now that flag should be properly set.
