### ISSUE TITLE
How to delete a saved search?

### ISSUE THREAD

**Issue by mjplimley** [d1vanov/quentier#393]
I'm running Quentier 0.5.0 on Ubuntu 20.04.

I have one saved search but it only comes up with 2 of 50 notes in the notebook. If I change the filter to blank instead of the Saved search and remove the tag, I get what I want.

Is there a way to delete the saved search since it is just getting in my way?

**Comment by d1vanov** [comment]
It depends on the type of account that you use in Quentier. If you use a local account, you can delete the saved search by right-clicking on it on the side view and choosing delete option in the context menu. However, if you use Quentier with Evernote account, you cannot delete any saved search - or any data other data item from your Evernote account for that matter - from inside Quentier. Evernote does not allow third party applications to permanently delete any data items from users' accounts. It's reasonable because Evernote cannot guarantee that some thirdparty application doesn't screw things up and permanently delete something by accident or even maliciously.

So if you want to delete something from your account permanently, you need to use some official Evernote client - web version or any desktop or mobile client app. Delete the data item there and then run sync in Quentier. It should recognize that the corresponding data item was deleted in Evernote and will delete the local counterpart.

**Comment by mjplimley** [comment]
Duh, that seems obvious now that you mention it. I deleted the search in Evernote and now Quentier works much better.

Thanks for pointing me in the right direction.

**Comment by d1vanov** [comment]
You're welcome!
