### ISSUE TITLE
[bug] Unable to launch GUI with filesystem on NVME drive

### ISSUE THREAD

**Issue by eashleyfl** [d1vanov/quentier#397]
**Describe the problem**
If the /home filesystem is on an NVME drive (mine is BTFS), the GUI reports that an instance is already running, though all that is running is the background update process:

`eric        2225    1843  0 Mar19 ?        00:04:13 /usr/bin/quentier-0.5.0 --startMinimizedToTray`

**Steps to reproduce the problem**
1. Go to 'Applications'
2. Click on either 'Internet' or 'Office
3. Click on 'Quentier'

**Expected behavior**
The GUI should launch normally. I have the same setup on a laptop with BTFS filesystem on an SSD drive and it works correctly. I am able  to `sqlite3 dump qn.storage.sqlite`  while the `--startMinimizedToTray` task is running, so it's not an OS level sharing problem.

**Environment info**
Please provide the information about the environment in which Quentier is run:
1. OS - Linux
2.  Fedora 37 Workstation
3. 0.5.0 from Fedora system repository
4. Fedora System repoository

**Screenshots**
![Screenshot from 2023-03-20 14-21-56](https://user-images.githubusercontent.com/1494350/226433166-fdcac01f-80fa-40c8-be51-04b97f390923.png)

**Additional context**
Killing the `--startMinimizedToTray` task allows the GUI to open correctly. I have not noticed any other oddities caused by the NVME drive, though I don't do much more that edit simple lists.

**Comment by d1vanov** [comment]
Hi there.
The issue you describe doesn't have anything to do with the filesystem or hard drive type. Quentier is designed to run as a single instance per account. This is why it doesn't allow you to run the second instance.

I don't know which DE you use, maybe Gnome? I don't use it myself but AFAIK it has dropped the concept of system tray from which I originally intended users to open the already running Quentier instance instead of the applications menu. If this behaviour is a problem for you, you can try to configure Quentier preferences such that it doesn't start automatically on login and/or doesn't start minimized to system tray.

**Comment by d1vanov** [comment]
> all that is running is the background update process

Well, nope, it's not an update process, it's actually the full fledged Quentier instance, only with main window hidden. And, as the command line argument shows, this instance is started minimized to system tray. If your DE has a system tray, you should be able to show the main window by clicking the icon in the system tray. Otherwise, as mentioned above, you can configure the app to nor start on login or not start minimized to system tray.

**Comment by eashleyfl** [comment]
Yes, it's Gnome. Oddly, the `Start at login` checkbox is NOT selected, but gnome is still using the choice from the list, which is defaulted to 'Start minimized to tray' and starting it anyway.
