### ISSUE TITLE
[question] "Preparing attachment images" modal

### ISSUE THREAD

**Issue by charlescanato** [d1vanov/quentier#405]
I'm just getting to know Quentier. I'm aware it's still in alpha stage, so I'm not sure one is supposed to create issues, but here I go.

There's a "preparing attachment images" that appears after you click over a note, about 1 or 2 secs later. It's a modal one, and it stays there forever. Really, nothing happens. I close it and can use Quentier normally, apparently.

It's not always shown, although it's shown on a note where I couldn't find any attachments. Anyway, I'm cleaning it to see if there's some hidden tag which is triggering this.

Taking a look at the code (master), it seems to me that nothing is really done after it's shown. The code which is supposed to run, is at another place (I anticipate apologies, I'm a pretty beginner C++ dev, although quite experienced in other envs), or really it's just unfinished stuff?

Thanks!

**Comment by d1vanov** [comment]
Hi there!
The code in question belongs in libquentier, Quentier's core library. It can be found [here](https://github.com/d1vanov/libquentier/blob/master/src/note_editor/NoteEditor_p.cpp#L3694-L3704). There's a condition above the code showing this dialog which checks that note does have resources and image resources in particular. 

Why you might be seeing this dialog on a note withoout attachments - because Quentier allows to open several notes at the same time in different tabs. So probably in some other inactive tab you actually have a note with image attachments.

The dialog was meant to let the user know that the note is being loaded, images would most likely be the last to appear and it's better to not start editing until the loading is complete to prevent potential issues. But the implementation probably doesn't live up to the expectation - the dialog should only be shown when the loading is slow (like, some seconds have already passed but it's still not finished) and only if the note editor widget is visible i.e. is in the foreground.

Probably the best thing to do given the circumstances would be to get rid of this dialog completely. If I ever manage to refactor the note editor's code, this functionality could be implemented more carefully and reasonably.

**Comment by charlescanato** [comment]
Such a quick reply! Thanks Dmitry, now I guess I got the idea, the note is already being loaded, the modal is just to give it some time.

As I said, I'm pretty much beginning in C++. Thanks a lot for your code, I had read that section (and wasn't sure if I was missing something), and may I say your code is very readable - ok, I just saw a few pieces. :-) I was trying to start through NixNote2 (and I still am), so I hope to benefit from two different codebases.

I'm still trying to understand the several traps of establishing a good Win dev environment for C++, still getting ready to build libquentier.

Anyway, thanks for such a quick commit! Will be around building Quentier soon, I hope.

**Comment by d1vanov** [comment]
I've updated the last [unstable build](https://github.com/d1vanov/quentier/releases/tag/continuous-development), it doesn't have this dialog anymore. Could you please give it a quick test, see if everything looks ok? If it is, I'd forward this fix to the stable version as well.

**Comment by charlescanato** [comment]
It is all okay! Notes still load successfully, no more modal dialogs about the attachments! Thanks!

(I don't know if, in your development cycle, I should reply closing the issue)

**Comment by d1vanov** [comment]
Merged the fix to master branch as well, thanks for checking the fix!
