### ISSUE TITLE
[bug] One changed note, sync, Failed to send new and/or mofidied notes to Evernote service

### ISSUE THREAD

**Issue by charlescanato** [d1vanov/quentier#408]
The initial download was full, and I even changed a few notes - and got them successfully synced.

Eventually, I got comfortable and started using Quentier as I want - to create/edit my notes. Searched for the term "quentier", filtering ok. Clicked on one of the notes I've wanted to edit, made small changes. Clicked on Sync button since I didn't want to wait for the autosync this time.

Then it started showing "downloading attachments: 2 of 2", "downloading notes: 2 of 2", and switching between them, with no more than a 10-sec interval. A duplicate of the note I've changed appeared with the suffix "- conflicting". I've stopped sync. Deleted the conflicting note. Tried to sync again. Same error message, but one second later, the crash window and the program closed.

Started it again - the sync on program start ran, showed the same strings, but this time it quickly showed the error msg from the title: "Failed to send new and/or mofidied notes to Evernote service". Both notes still there: the original and the conflicting one, both with "needs sync" icon. Deleted the conflicting one. Clicking sync still gives the error msg. Deleted the conflicting note. Tried to sync: same error.

Also tried to change note between notebooks. Same problem.

Exported the note to ENEX, deleted it, tried to sync. Now the note can't be found anymore, but I still have the error msg. Of course, I reimported the ENEX, but I know the original one is somewhere there. No change, still blocked from uploading any changes.

**Expected behavior**
Change a note and get it synced.

**Environment info**
Please provide the information about the environment in which Quentier is run:
1. OS: **Windows**
3. Which version of Quentier do you use - latest **unstable**
4. Where did you install Quentier from - **downloaded from GitHub releases**

**Additional context**
I'm also attaching a debug log of one of these tries. Please remove it when you have it - or just warn me and I'll remove it.

Hope the description and log are useful. Thanks!

**Comment by d1vanov** [comment]
It seems you didn't attach the debug log or at least I cannot find it anywhere within your message.
If you are not comfortable to share the logs here, you can e-mail them to me: `dm.vl.ivanov@gmail.com`

> Same error message, but one second later, the crash window and the program closed.

It should have shown some technical information about the crash. In future if you see crashes, it'd be valuable to report them as separate issues and attach the collected info as it might help in troubleshooting.

**Comment by d1vanov** [comment]
In general, current Quentier's approach to synchronization is not ideal to say the least - I followed Evernote's [document](https://dev.evernote.com/media/pdf/edam-sync.pdf) on how to do sync and decided that panicking and stopping on every single error is good enough tactic as it at least helps to maintain consistency of data in the account. I can see now that it's far from ideal behaviour. For the past two years I've been redesigning first the local storage layer of Quentier and then the synchronization logic. When I'm ready to release it, it would try as hard as it can to tolerate errors of sending some particular notes, notebooks, tags etc. and try to send other data items nevertheless. Same principle would be also used for downloading of notes and attachments - if something fails, it fails but nonetheless sync of other data items would be attempted at least.

Also why deleting the note would not help: Quentier doesn't delete notes permanently, instead it just marks them as deleted so they go to the "trash bin". It's the same approach as Evernote uses. If I remember correctly, currently for Evernote accounts Quentier users have no ability to permanently delete anything (other than note's contents). The reason is that Evernote API doesn't allow any thirdparty apps to permanently delete anything from the account, you can only do so via official Evernote apps (including web version). Perhaps it should be allowed in Quentier to permanently delete stuff which has never been synced with Evernote yet i.e. things which Evernote service has no knowledge about.

**Comment by charlescanato** [comment]
Totally my fault. I wrote the report and completely forgot to attach the logs. I'm sending them directly to your e-mail address, thanks (and feel free to erase it, in case you don't want it here for any spammer).

About the deletion, yes, I'm aware of the restriction. I was just really checking if Quentier, as you said, would drop it considering it had not been uploaded.

**Comment by d1vanov** [comment]
Thanks, I received your logs and tried to analyze them. It seems that the origin of the problem is that there is some new note you created which appears to have an attachment but its data body is empty. And Evernote thus refuses to accept such a note.

So what I can offer as a short term hacky solution:
1. I tried to improve the logs so that a failure to send some note would print the detailed information about the offending note so it can at least be identified.
2. I've made it possible to permanently delete notes which are already in the trash folder including both notes which were not yet synchronized with Evernote AND notes which Evernote service is aware of. Since Evernote doesn't allow such permanent deletions from third party apps, the deletion would only affect Quentier's local database but it won't be propagated back to Evernote service.

So with [the latest unstable build](https://github.com/d1vanov/quentier/releases/tag/continuous-development) you should be able to:
1. Try to sync once again - it would fail with the same error
2. But this time the warning log should show which exact note causes this error
3. Then if this note is not yet in the trash folder (in the log such note would have `deleted = <timestamp>` instead of `deleted is not set`), you can try to delete it i.e. move it to the trash folder.
4. You can enable the side view with deleted notes by choosing `View` menu -> `Side panel` and then enabling `Show deleted notes` checkbox.
5. Then in the view with deleted notes find that offending note, right click on it and select `Delete permanently` option. In your case this note has not yet been sent to Evernote so it shouldn't cause any further problems with the sync.

Can you please try it and let me know whether it helps?

Regarding the origin of the problem that the note has somehow lost the attachment data: I'm not sure how it happened and I guess it's close to impossible to figure it out by now. In theory it might be the effect of not fully transactionally safe way that local storage uses to store binary data of the attachments. Just to let you know, right now I'm trying to finish the major refactoring of both local storage and synchronization (briefly described in d1vanov/libquentier#181 and d1vanov/libquentier#206). Right now I'm at the stage of writing integrational tests for synchronization and debugging things using them. There's hope that in several months I might be able to prepare these new refactored implementations for unstable branch. No promises though, I've already behind schedule...

**Comment by charlescanato** [comment]
@d1vanov , I apologize for taking some time to check here again. I just read these great news, thanks for spending your time to check my logs. Right now, I'm on phone, but later today I'll check the results and find this picky note of mine. Thank you so much!

**Comment by charlescanato** [comment]
Finally, here I am. First things first: it worked greatly for removing the offending note. I opened the deleted notes, removed all of those which were not synced, and sync finished! :-)

But... then I've updated some notes, and Quentier entered in a state where it wasn't marking notes as "to-sync" anymore, and of course, trying to sync didn't make any difference. I've closed it and thought I just could reproduce that later, as I've mentioned in the previous message.

I just opened Quentier again, pressed Sync, since I've been handling notes the last days on Android EN and NixNote2. As soon as I've opened it, now I could see the "to-sync" mark on the two notes I've updated that time. I've tried to sync, it download updates from EN, but then it crashed when trying to upload. I've already separated the minidump and crash info for this.

Opened Quentier again. Updated a note which was **not** marked for sync. Tried to sync. It gives me an error msg, but no crash this time.

So, I'm doing it again in hopes I can reproduce that just like the previous paragraph. Will collect trace logs during a note change, then will sync and when it gives the error, will send those files to you like before.

I'm just advancing what I feel you might need to debug. I know you have limited time for this, and is changing the core, no strings attached. Whenever you have the time, and IF it makes sense, you can ask me for any new tests, data and so.

**Comment by charlescanato** [comment]
Finally, here I am. First things first: it worked greatly for removing the offending note. I opened the deleted notes, removed all of those which were not synced, and sync finished! :-)

But... then I've updated some notes, and Quentier entered in a state where it wasn't marking notes as "to-sync" anymore, and of course, trying to sync didn't make any difference. I've closed it and thought I just could reproduce that later, as I've mentioned in the previous message.

I just opened Quentier again, pressed Sync, since I've been handling notes the last days on Android EN and NixNote2. As soon as I've opened it, now I could see the "to-sync" mark on the two notes I've updated that time. I've tried to sync, it download updates from EN, but then it crashed when trying to upload. I've already separated the minidump and crash info for this.

Opened Quentier again. Updated a note which was **not** marked for sync. Tried to sync. It gives me an error msg, but no crash this time.

So, I'm doing it again in hopes I can reproduce that just like the previous paragraph. Will collect trace logs during a note change, then will sync and when it gives the error, will send those files to you like before.

One thing I've noticed. I have Deleted Notes panel open, with two notes there. On both of them, "Delete Permanently" is available, however when trying to delete, it gives me an internal error on a msgbox: "The note model refused to delete the note permanently; Check the status bar for message from the note model explaining why the action was not successful". However, no status bar message appears.

I've collected a trace log for that, but it **seemed** to me that there's no valuable information there. It has two msgs for the context menu delete operation and then just another mentioning it failed, and all of the other traces seems to be only from the UI updates. Anyway, I've collected it.

I'm just anticipating what I feel you might need to diagnose. I know you have limited time for this, and is changing the core, no strings attached. Whenever you have the time, and IF it makes sense, you can ask me for any new tests, data and so.

In the mean time, I will try to establish a dev env here, I use vim for most of my change tests, but I feel an IDE with a decent debugger will serve me better for this kind of debugging. No promises, I'm still starting on this.

**Comment by d1vanov** [comment]
It appears that I have overlooked one detail about permanently deleting the notes which were already synchronized with Evernote, I'll need to fix it. Basically [this fragment](https://github.com/d1vanov/quentier/blob/master/lib/model/note/NoteModel.cpp#L3093-L3101) of code would need to be removed.

About other issues:
1. Notes not marked as locally modified - the only clue I have without logs is that notes are marked as locally modified as soon as their content from the editor is saved to the database. It should happen automatically with some period while the editor is idle and then when the editor is closed. However, you can trigger saving manually by pressing the corresponding icon or hitting the Ctrl+S shortcut. Logs would be helpful so feel free to file a separate issue for that problem.
2. About the crash - minidump and stack trace are essential to try and understand its cause. Again, you can file it as a separate issue.

About setting the dev env - I have a [wiki](https://github.com/d1vanov/quentier/wiki) with some articles which might be helpful. In particular, [this article](https://github.com/d1vanov/quentier/wiki/Building-and-installation-of-Quentier's-dependencies) talks about building of Quentier's dependencies, it has a [section](https://github.com/d1vanov/quentier/wiki/Building-and-installation-of-Quentier's-dependencies#windows) about Windows. Beyond these dependencies you'll need to build and install [QEverCloud](https://github.com/d1vanov/QEverCloud#how-to-build) and [libquentier](https://github.com/d1vanov/libquentier/blob/master/INSTALL.md) and then [build and install](https://github.com/d1vanov/quentier/blob/master/INSTALL.md) Quentier itself.

**Comment by d1vanov** [comment]
The issue with notes once synchronized with Evernote refusing to be permanently deleted should be fixed now in the latest [unstable release](https://github.com/d1vanov/quentier/releases/tag/continuous-development).

**Comment by charlescanato** [comment]
Thanks again @d1vanov ! As you released a new unstable build, I'll repeat my tries above, so I can collect logs separately for each issue - and you're right, it surely makes much more sense to separate each issue, sorry for building a small mess here.

Going to test (and collect logs, if needed)! :-)

**Comment by charlescanato** [comment]
> The issue with notes once synchronized with Evernote refusing to be permanently deleted should be fixed now in the latest [unstable release](https://github.com/d1vanov/quentier/releases/tag/continuous-development).

Confirmed! I was able to delete every note that was pending sync in Deleted Notes. :-)

**Comment by d1vanov** [comment]
One thing which I realized from logs to #412 is how you managed to end up with a note which contains a resource without body - it appears that you had a todo checkbox within the note and then you copy-pasted a fragment of note containing the said checkbox. The copy-paste logic did not realize the checkbox is, well, just a checkbox, instead it was treated as a fragment of HTML with a picture inside it. The logic attempted to save the picture as an attachment but it seems that it failed to fetch the actual data of the picture because it was embedded into the app but not accessible through an external hyperlink.
I'll create a separate issue about that a bit later.

**Comment by charlescanato** [comment]
oops, sorry, I ended up updating my last comment without noticing you already replied

**Comment by charlescanato** [comment]
> One thing which I realized from logs to #412 is how you managed to end up with a note which contains a resource without body - it appears that you had a todo checkbox within the note and then you copy-pasted a fragment of note containing the said checkbox. The copy-paste logic did not realize the checkbox is, well, just a checkbox, instead it was treated as a fragment of HTML with a picture inside it. The logic attempted to save the picture as an attachment but it seems that it failed to fetch the actual data of the picture because it was embedded into the app but not accessible through an external hyperlink. I'll create a separate issue about that a bit later.

Some of my recent findings involve exactly that. You are possibly checking the same note as me, if I select it all, create a new note and paste, some weird things start to happen in the editor. Well, I'll describe it better tomorrow, because it also involves an error and the note getting uploaded.

Thanks again for the deletion magic! :-)

**Comment by charlescanato** [comment]
> @charlescanato just in case, I fixed copy-pasting note fragments with todos + fixed two different crash reasons, it's all ready in the latest [unstable build](https://github.com/d1vanov/quentier/releases/tag/continuous-development). I'll get these fixes to the stable branch as well.

That was a great fix, @d1vanov ! I didn't even register the bug, but indeed sometimes when I was pasting fragments with todos, I was having some problems, even being limited to editing within the todo "image space".

Now the pastes seem to be working as expected. :-)
